"""add oauth column

Revision ID: f464c0333f81
Revises: 5e70c3d6b08e
Create Date: 2021-03-20 20:29:11.706343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f464c0333f81'
down_revision = '5e70c3d6b08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('oauth', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('usuario', 'oauth')
    # ### end Alembic commands ###
